production:
  delivery_method: :smtp
  smtp_settings:
    enable_starttls_auto: true
    address: <%= ENV["MAIL_SMTP_ADDRESS"] %>
    port: <%= ENV["MAIL_SMTP_PORT"] %>
    authentication: :plain
    domain: <%= ENV["MAIL_SMTP_DOMAIN"] %>
    user_name: <%= ENV["MAIL_SMTP_USER"] %>
    password: <%= ENV["MAIL_SMTP_PASSWORD"] %>
