production:
  delivery_method: :smtp
  smtp_settings:
    address: <%= ENV["MAILGUN_SMTP_SERVER"] %>
    port: <%= ENV["MAILGUN_SMTP_PORT"] %>
    authentication: :plain
    domain: "agile-mesa-37158.herokuapp.com"
    user_name: <%= ENV["MAILGUN_SMTP_LOGIN"] %>
    password: <%= ENV["MAILGUN_SMTP_PASSWORD"] %>
