production:
  delivery_method: :smtp
  smtp_settings:
    enable_starttls_auto: true
    address: "smtp.office365.com" 
    port: '587'
    domain: "limaelorenzoni.com" 
    authentication: :login
    user_name: "limalorenzoni@hotmail.com" 
    password: "gremistas" 

#production:
#  delivery_method: :smtp
#  smtp_settings:
#    address: <%= ENV["MAILGUN_SMTP_SERVER"] %>
#    port: <%= ENV["MAILGUN_SMTP_PORT"] %>
#    authentication: :plain
#    domain: <%= ENV["MAILGUN_DOMAIN"] %>
#    user_name: <%= ENV["MAILGUN_SMTP_LOGIN"] %>
#    password: <%= ENV["MAILGUN_SMTP_PASSWORD"] %>
